log_level = "info"
log_path = "/tmp"
job_timeout = 60

[net]
worker_listen = "0.0.0.0"
worker_port = 5566
log_ingestion_listen = "0.0.0.0"
log_ingestion_port = 5568

[app]

[datastore]
user = "hab"
password = ""
database = "builder_jobsrv"
connection_retry_ms = 300
connection_timeout_sec = 3600

[archive]
backend = "local"
